package com.mas.mobile.repository.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.mas.mobile.presentation.activity.converter.MoneyConverter
import com.mas.mobile.repository.db.config.AppDatabase.Companion.AUTOGENERATED
import java.time.LocalDate
import java.util.Currency

@Entity(tableName = "budgets", indices = [Index(value = ["name"], unique = true)])
data class Budget(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    override var id: Int = AUTOGENERATED,

    @ColumnInfo(name = "name")
    override var name: String = "",

    @ColumnInfo(name = "plan")
    var plan: Double = 0.0,

    @ColumnInfo(name = "fact")
    var fact: Double = 0.0,

    @ColumnInfo(name = "startsOn")
    var startsOn: LocalDate = LocalDate.now(),

    @ColumnInfo(name = "lastDayAt")
    var lastDayAt: LocalDate = LocalDate.now(),

    @ColumnInfo(name = "isActive")
    var isActive: Boolean = false,

    @ColumnInfo(name = "comment")
    var comment: String? = "",

    @ColumnInfo(name = "currency")
    var currency: String
): Searchable(id, name)

