package com.mas.mobile.repository.db.entity

import androidx.room.*
import androidx.room.ForeignKey.Companion.CASCADE
import com.mas.mobile.repository.db.config.AppDatabase.Companion.AUTOGENERATED

data class Expenditure(
    @Embedded
    var data: ExpenditureData,

    @Relation(
        parentColumn = "budget_id",
        entityColumn = "id"
    )
    var budget: Budget
) : Comparable {
    var id: Int
        get() = data.id
        set(value) { data.id = value }

    var name: String
        get() = data.name
        set(value) { data.name = value }

    var plan: Double
        get() = data.plan
        set(value) { data.plan = value }

    var fact: Double
        get() = data.fact
        set(value) { data.fact = value }

    var comment: String?
        get() = data.comment
        set(value) { data.comment = value }

    override fun getKey() = id
}

@Entity(tableName = "expenditures",
        foreignKeys = [
            ForeignKey(entity = Budget::class,
            parentColumns = ["id"],
            childColumns = ["budget_id"],
            onDelete = CASCADE)],
        indices = [
            Index(value = ["budget_id"]),
            Index(value = ["budget_id", "display_order", "name"], name = "index_expenditures_on_budget_order_name"),
            Index(value = ["name"], name = "index_expenditures_on_name")
        ]
)
data class ExpenditureData(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    override var id: Int = AUTOGENERATED,

    @ColumnInfo(name = "name")
    override var name: String = "",

    @ColumnInfo(name = "plan")
    var plan: Double = 0.0,

    @ColumnInfo(name = "fact")
    var fact: Double = 0.0,

    @ColumnInfo(name = "comment")
    var comment: String? = null,

    @ColumnInfo(name = "budget_id")
    var budget_id: Int = 0,

    @ColumnInfo(name = "icon")
    val icon: Int?,

    @ColumnInfo(name = "display_order")
    val display_order: Int = 0
): Searchable(id, name)