package com.mas.mobile.repository.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.mas.mobile.repository.db.config.AppDatabase.Companion.AUTOGENERATED
import java.util.Currency

@Entity(tableName = "message_rules")
data class MessageRule(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    override var id: Int = AUTOGENERATED,

    @ColumnInfo(name = "name")
    override var name: String = "",

    @ColumnInfo(name = "amount_matcher")
    var amountMatcher: String = "{amount}",

    @ColumnInfo(name = "expenditure_matcher")
    var expenditureMatcher: String = "",

    @ColumnInfo(name = "expenditure_name")
    var expenditureName: String = "",

    @ColumnInfo(name = "currency")
    var currency: String
): Searchable(id, name)