package com.mas.mobile.repository.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.mas.mobile.repository.db.config.AppDatabase.Companion.AUTOGENERATED
import java.util.Currency

@Entity(tableName = "message_template")
data class MessageTemplate(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    var id: Int = AUTOGENERATED,

    @ColumnInfo(name = "sender")
    var sender: String,

    @ColumnInfo(name = "pattern")
    var pattern: String,

    @ColumnInfo(name = "example")
    var example: String,

    @ColumnInfo(name = "currency")
    var currency: String,

    @ColumnInfo(name = "enabled")
    var isEnabled: Boolean = true
)