package com.mas.mobile.repository.db.entity

import androidx.room.*
import com.mas.mobile.repository.db.config.AppDatabase.Companion.AUTOGENERATED

data class MessageRule(
    @Embedded
    var data: MessageRuleData,

    @Relation(
        parentColumn = "expenditure_id",
        entityColumn = "id"
    )
    var expenditure: ExpenditureData
) : Comparable {
    var id: Int
        get() = data.id
        set(value) { data.id = value }

    var name: String
        get() = data.name
        set(value) { data.name = value }

    var amountMatcher: String
        get() = data.amountMatcher
        set(value) { data.amountMatcher = value }

    var expenditureMatcher: String
        get() = data.expenditureMatcher
        set(value) { data.expenditureMatcher = value }

    var expenditureId: Int
        get() = data.expenditureId
        set(value) {
            data.expenditureId = value
            expenditure.id = value
        }

    override fun getKey() = id
}

@Entity(tableName = "message_rules")
data class MessageRuleData(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    override var id: Int = AUTOGENERATED,

    @ColumnInfo(name = "name")
    override var name: String = "",

    @ColumnInfo(name = "amount_matcher")
    var amountMatcher: String = "{amount}",

    @ColumnInfo(name = "expenditure_matcher")
    var expenditureMatcher: String = "",

    @ColumnInfo(name = "expenditure_id")
    var expenditureId: Int = -1,
): Searchable(id, name)