package com.mas.mobile.repository.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.mas.mobile.repository.db.config.AppDatabase
import com.mas.mobile.repository.db.config.AppDatabase.Companion.AUTOGENERATED

@Entity(
    tableName = "qualifiers",
    indices = [Index(value = ["type", "name"], name = "index_qualifiers_on_type_name")]
)
data class Qualifier(
    @PrimaryKey
    @ColumnInfo(name = "id")
    var id: Int = AUTOGENERATED,

    @ColumnInfo(name = "name")
    var name: String = "",

    @ColumnInfo(name = "type")
    var type: Short = 0,
) {
    companion object {
        const val CATCH: Short = 1
        const val SKIP: Short = 2
        const val BLACKLIST: Short = 3
    }
}
