package com.mas.mobile.repository.db.entity

import androidx.room.Ignore
import com.mas.mobile.repository.db.config.AppDatabase.Companion.AUTOGENERATED

abstract class Searchable(
    @Ignore
    open val id: Int = AUTOGENERATED,

    @Ignore
    open val name: String
) : Comparable {
    override fun getKey() = id
}

interface Comparable {
    fun getKey(): Int
}