package com.mas.mobile.repository.db.entity

import androidx.room.*
import com.mas.mobile.repository.db.config.AppDatabase.Companion.AUTOGENERATED
import java.time.LocalDateTime

data class SpendingMessage(
    @Embedded
    var data: SpendingMessageData,

    @Relation(
        parentColumn = "spending_id",
        entityColumn = "id"
    )
    var spending: SpendingData? = null,

    @Relation(
        parentColumn = "suggested_expenditure_id",
        entityColumn = "id"
    )
    var suggestedExpenditure: ExpenditureData? = null
) : Comparable {
    var id: Int
        get() = data.id
        set(value) { data.id = value }

    var name: String
        get() = data.name
        set(value) { data.name = value }

    var message: String
        get() = data.message
        set(value) { data.message = value }

    var receivedAt: LocalDateTime
        get() = data.receivedAt
        set(value) { data.receivedAt = value }

    var ruleId: Int
        get() = data.ruleId
        set(value) { data.ruleId = value }

    var spendingId: Int?
        get() = data.spendingId
        set(value) { data.spendingId = value }

    var suggestedExpenditureId: Int?
        get() = data.suggestedExpenditureId
        set(value) { data.suggestedExpenditureId = value }

    var suggestedAmount: Double?
        get() = data.suggestedAmount
        set(value) { data.suggestedAmount = value }

    override fun getKey() = id
}

@Entity(tableName = "spending_messages",
    foreignKeys = [
        ForeignKey(entity = SpendingData::class,
            parentColumns = ["id"],
            childColumns = ["spending_id"],
            onDelete = ForeignKey.SET_NULL
        )])
data class SpendingMessageData(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    override var id: Int = AUTOGENERATED,

    @ColumnInfo(name = "name")
    override var name: String = "",

    @ColumnInfo(name = "message")
    var message: String = "",

    @ColumnInfo(name = "receivedAt")
    var receivedAt: LocalDateTime = LocalDateTime.now(),

    @ColumnInfo(name = "rule_id")
    var ruleId: Int = -1,

    @ColumnInfo(name = "spending_id")
    var spendingId: Int? = null,

    @ColumnInfo(name = "suggested_expenditure_id")
    var suggestedExpenditureId: Int? = null,

    @ColumnInfo(name = "suggested_amount")
    var suggestedAmount: Double? = null,

    ): Searchable(id, name)
