package com.mas.mobile.repository.db.entity

import androidx.room.*
import com.mas.mobile.repository.db.config.AppDatabase.Companion.AUTOGENERATED
import java.time.LocalDateTime
import java.util.Currency

data class Spending (
    @Embedded
    var data: SpendingData,

    @Relation(
        parentColumn = "expenditure_id",
        entityColumn = "id"
    )
    var expenditure: ExpenditureData
) : Comparable {
    var id: Int
        get() = data.id
        set(value) { data.id = value }

    var comment: String?
        get() = data.comment
        set(value) { data.comment = value }

    var date: LocalDateTime
        get() = data.date
        set(value) { data.date = value }

    var amount: Double
        get() = data.amount
        set(value) { data.amount = value }

    var expenditureId: Int
        get() = data.expenditureId
        set(value) { data.expenditureId = value }

    override fun getKey() = id
}

@Entity(tableName = "spendings",
        foreignKeys = [
            ForeignKey(entity = ExpenditureData::class,
                parentColumns = ["id"],
                childColumns = ["expenditure_id"],
                onDelete = ForeignKey.CASCADE
            )],
        indices = [Index(value = ["expenditure_id"])]
)
data class SpendingData (
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    var id: Int = AUTOGENERATED,

    @ColumnInfo(name = "comment")
    var comment: String? = "",

    @ColumnInfo(name = "date")
    var date: LocalDateTime = LocalDateTime.now(),

    @ColumnInfo(name = "amount")
    var amount: Double = 0.0,

    @ColumnInfo(name = "expenditure_id")
    var expenditureId: Int = 0,

    @ColumnInfo(name = "currency")
    var currency: String? = null,

    @ColumnInfo(name = "rate")
    var rate: Double? = null,

    @ColumnInfo(name = "foreignAmount")
    var foreignAmount: Double? = null
)